/* Automatically generated by './build/bin/build-entry.js' */

import Input from '../packages/input/index.js';
import ElCity from '../packages/el-city/index.js';
import Loading from '../packages/loading/index.js';
import locale from 'element-ui/src/locale';

const components = [
  Input,
  ElCity
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });
  Vue.use(Loading.directive);
  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
  Vue.prototype.$loading = Loading.service;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Loading,
  Input,
  ElCity
};
